default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= Rails.application.secrets[:database_host] %>
  username: <%= Rails.application.secrets[:database_username] %>
  password: <%= Rails.application.secrets[:database_password] %>
  port: 5432

development:
  <<: *default
  database: <%= %Q|#{Rails.root.to_s.split("/").last}_development| %>

test:
  <<: *default
  database: <%= %Q|#{Rails.root.to_s.split("/").last}_test| %>

production:
  <<: *default
  database: d234b7eql9vpov

