shared:
  instagram_cliend_id: <%= ENV["INSTAGRAM_CLIENT_ID"] %>
  instagram_cliend_secret: <%= ENV["INSTAGRAM_CLIENT_SECRET"] %>

default: &database
  database_host: localhost
  database_username: postgres
  database_password: postgres

development:
  secret_key_base: d699a582a387d05d7b1571832d81c9b34f60e5dc985ce0ba7c7b062b16a0cc4c8eb9a2c00477f6bd6c355e80a83d4aa595aa13df5150de9aa74abfa950cbb802
  <<: *database


test:
  secret_key_base: 42d881314398289546d656079f94e1ab41af14c28bdaefbf4e9edbd33a9b7f3053851ec532e5d3665c7fdf54c353a6475a919abbddf6b994774fc3da9b6ccc94
  <<: *database

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database_host: <%= ENV["DATABASE_HOST"] %>
  database_username: <%= ENV["DATABASE_USERNAME"] %>
  database_password: <%= ENV["DATABASE_PASSWORD"] %>
